import cv2
import numpy as np


class BGSConfig:
    TARGET_CLASSES = {
        0: 'person',
        24: 'backpack',
        26: 'handbag',
        28: 'suitcase'
    }
    CLASS_IDS = list(TARGET_CLASSES)
    EXPECTED_CLASS_IDS = set(TARGET_CLASSES)
    EXPECTED_TARGET_CLASSES = TARGET_CLASSES
    PERSON_CLASS_ID = 0
    BAG_CLASS_IDS = [24, 26, 28]
    DETECTION_CONFIDENCE = 0.20
    PERSON_CONF = 0.18
    BAG_CONF = DETECTION_CONFIDENCE - 0.05
    IOU_THRESHOLD = 0.45

    TRACKER = "bytetrack.yaml"
    PERSIST = True
    TRACK_BUFFER = 90
    TRACK_THRESH = 0.25
    MATCH_THRESH = 0.6
    BAG_MATCH_THRESHOLD_PX = 100
    BAG_FRAME_MEMORY = 30

    CAMERA_HFOV = 60.0
    ASSUMED_PERSON_HEIGHT = 1.70
    ASSUMED_BAG_HEIGHT = 0.45
    IMAGE_WIDTH = 1280
    IMAGE_HEIGHT = 720
    FOCAL_LENGTH = (IMAGE_WIDTH / 2) / np.tan(np.radians(CAMERA_HFOV / 2))
    DETECTION_RESCUE_ENABLED = True
    DETECTION_RESCUE_RECENT_FRAMES = 12
    DETECTION_RESCUE_PERSON_CONF = 0.14
    DETECTION_RESCUE_BAG_CONF = 0.10

    DISTANCE_HISTORY_SIZE = 30
    ASSIGNMENT_DISTANCE = 2.5
    CONFIRMATION_TIME = 2.0
    OWNERSHIP_LOCK_TIME = 10.0
    SWITCH_DISTANCE_IMPROVEMENT = 1.5

    POTENTIAL_THRESHOLD = 5.0
    UNATTENDED_THRESHOLD = 10.0
    OWNERSHIP_RELEASE_GRACE = 5.0

    REID_MAX_AGE_FRAMES = 900
    REID_MATCH_MAX_AGE_FRAMES = 240
    REID_APPEARANCE_MAX_AGE_FRAMES = 600
    REID_GEOMETRY_PRIORITY_MAX_AGE_FRAMES = 12
    REID_CENTROID_THRESH = 80
    REID_BAG_CENTROID_THRESH = 60
    REID_IOU_THRESH = 0.25
    REID_PERSON_MODEL_NAME = "osnet_x1_0"
    REID_PERSON_MODEL_PATH = "models/reid/osnet_x1_0_msmt17.pt"
    REID_PERSON_EMBED_THRESHOLD = 0.58
    REID_PERSON_INPUT_SIZE = (256, 128)
    REID_PERSON_MIN_CROP_SIZE = 32
    REID_PERSON_SIZE_RATIO_MIN = 0.40
    REID_PERSON_ASPECT_RATIO_MAX_DIFF = 0.55
    REID_APPEARANCE_UPDATE_WEIGHT = 0.20
    REID_PERSON_GALLERY_SIZE = 12
    REID_PERSON_APPEARANCE_PRIORITY = 0.04
    REID_BAG_APPEARANCE_MAX_AGE_FRAMES = 600
    REID_BAG_EMBED_THRESHOLD = 0.66
    REID_BAG_MIN_CROP_SIZE = 20
    REID_BAG_SIZE_RATIO_MIN = 0.45
    REID_BAG_ASPECT_RATIO_MAX_DIFF = 0.90
    REID_BAG_GALLERY_SIZE = 8
    REID_BAG_OWNER_MATCH_BONUS = 0.14
    REID_BAG_APPEARANCE_PRIORITY = 0.05
    REID_BAG_CLASS_MISMATCH_PENALTY = 0.03
    REID_PERSON_PERSIST_PATH = "logs/person_reid/person_registry.pkl"
    REID_PERSON_PERSIST_LOG_DIR = "logs/person_reid"
    REID_BAG_PERSIST_PATH = "logs/bag_reid/bag_registry.pkl"
    REID_BAG_PERSIST_LOG_DIR = "logs/bag_reid"
    REID_PERSIST_INTERVAL_FRAMES = 30
    REID_PERSIST_MAX_AGE_SECONDS = 43200.0
    REID_FRAME_IMAGE_DIRNAME = "frames"
    REID_FRAME_METADATA_NAME = "frames.jsonl"
    REID_FRAME_IMAGE_EXT = ".jpg"

    COLOR_PERSON = (50, 205, 50)
    COLOR_BAG_OK = (255, 165, 0)
    COLOR_BAG_POTENTIAL = (0, 165, 255)
    COLOR_BAG_UNATTENDED = (0, 0, 255)
    COLOR_DISTANCE_LINE = (255, 255, 0)
    COLOR_TEXT = (255, 255, 255)
    COLOR_BG = (30, 30, 30)
    COLOR_HIGHLIGHT = (0, 255, 255)
    SHOW_DISTANCE_LINES = True
    SHOW_DISTANCE_LABELS = True
    SHOW_DEBUG_OVERLAY = True
    LINE_THICKNESS = 3
    FONT_SCALE = 0.7
    FONT = cv2.FONT_HERSHEY_SIMPLEX